services:
    headless-desktop:
        container_name: headless-desktop
        build: ./docker/
        volumes:
            - "./config:/home/config"
        # environment:
        #   - TZ=America/Sao_Paulo
